import sys
from player import Player

# list all vent types
EVENT_CLASS_INPUT = 0
EVENT_CLASS_SERVER = 1
EVENT_CLASS_FINAL = 2

EVENT_CLASSES = [EVENT_CLASS_INPUT, EVENT_CLASS_SERVER, EVENT_CLASS_FINAL]


class EventManager(object):
    """handles the events between managers in the game"""

    def __init__(self):
        # initialize the right queues for each type
        # loops the event types creating a list for each of those
        self.subscriberQueues = dict()
        for eventClass in EVENT_CLASSES:
            self.subscriberQueues[eventClass] = list()

    # publishes an event of eType. eType must have been defined. returns success on ok publishing
    def publishEvent(self, event):
        # TODO check for the right queue. contact all subscribers.
        for subscriber in self.subscriberQueues[event.eclass]:
            subscriber.onEvent(event.eclass, event)

    # adds a new class to the subscriber to that eType. return success on ok subscription
    def subscribe(self, eclass, subscriber):
        # TODO check for the right queue. add subscriber to queue
        self.subscriberQueues[eclass].append(subscriber)

    # deletes the new class from the queue. return success on ok subscription
    def unsubscribe(self, eclass, subscriber):
        # TODO check for the right queue. delete subscriber to queue
        self.subscriberQueues[eclass].remove(subscriber)

    def start(self):
        pass

    def stop(self):
        pass


class EventSubscriber(object):
    """represents a subscriber of events"""

    def onEvent(self, eclass, event):
        raise NotImplemented


class Event(object):
    """represents an event in the game"""

    def __init__(self, eclass):
        self.eclass = eclass

class EventClassInput(Event):
    """represents the events generated by the user"""

    TYPE_SPEED = 0
    TYPE_MOVE_DIRECTION = 1
    TYPE_FACE_DIRECTION = 2
    TYPE_TURBO = 3
    TYPE_EXIT = 4

    def __init__(self, etype, properties):
        super(EventClassInput, self).__init__(EVENT_CLASS_INPUT)
        self.etype = etype
        self.properties = properties

class EventClassServer(Event):
    """represents the events provided by the server"""

    TYPE_SPEED = 0
    TYPE_MOVE_DIRECTION = 1
    TYPE_FACE_DIRECTION = 2
    TYPE_TURBO = 3
    TYPE_EXIT = 4

    def __init__(self, etype, properties):
        super(EventClassInput, self).__init__(EVENT_CLASS_INPUT)
        self.etype = etype
        self.properties = properties

class EventClassFinal(Event):
    """represents the events provided by the server"""

    TYPE_SPEED = 0
    TYPE_MOVE_DIRECTION = 1
    TYPE_FACE_DIRECTION = 2
    TYPE_TURBO = 3
    TYPE_EXIT = 4

    def __init__(self, etype, properties):
        super(EventClassInput, self).__init__(EVENT_CLASS_INPUT)
        self.etype = etype
        self.properties = properties



# class EventPlayerMove(Event):
#     """represents an event for a player moving"""

#     def __init__(self, player, move):
#         super(EventPlayerMove, self).__init__(EVENT_TYPE_PLAYER_MOVE)
#         self.player = player
#         self.move = move

# class EventPlayerDirect(Event):
#     """represents an event for a player changeing position"""

#     def __init__(self, player, direction):
#         super(EventPlayerDirect, self).__init__(EVENT_TYPE_PLAYER_REDIRECT)
#         self.player = player
#         self.direction = direction

